const GASURL = "https://script.google.com/macros/s/AKfycbzFlhCuwaJenjoOJAKrLa-VLvAfDWpQyqwtQgmDte5is0MLdCpJ9NMWq_rvGC84nObX/exec";

function toggleRuby() { document.body.classList.toggle('show-ruby'); }

function googleTranslateElementInit() { new google.translate.TranslateElement({ pageLanguage: 'ja', includedLanguages: 'ja,en,zh-CN', layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element'); }

document.addEventListener('DOMContentLoaded', () => { const nav = document.querySelector('nav'); if (nav) { nav.innerHTML = <div class="nav-inner"> <div class="nav-top"> <a href="index.html" class="nav-logo-area"> <img src="logo.jpg" class="nav-logo-img"> <span>KIZUNA video</span> </a> <button onclick="toggleRuby()" style="font-size:11px; padding:8px 14px; border-radius:14px; border:1.5px solid var(--accent); background:none; color:var(--accent); font-weight:bold; cursor:pointer;">よみがな表示</button> </div> <div class="nav-bottom"> <a href="about.html" class="nav-btn">ABOUT</a> <a href="works.html" class="nav-btn">WORKS</a> <a href="guide.html" class="nav-btn">GUIDE</a> <a href="reserve.html" class="nav-btn">RESERVE</a> <a href="download.html" class="nav-btn">DOWNLOAD</a> </div> </div>; } });

async function checkAuth() { const pw = document.getElementById('pw').value; const btn = document.getElementById('authBtn'); if(!pw) return alert("パスワードを入力してください"); btn.innerText = "照合中..."; btn.disabled = true; try { const res = await fetch(GASURL); const data = await res.json(); const match = data.find(i => i.password === pw); if (match) { document.getElementById('ui').style.display = 'none'; const dl = document.getElementById('dl'); dl.href = "https://drive.google.com/uc?export=download&id=" + match.file_id; dl.style.display = 'block'; } else { alert("パスワードが正しくありません"); btn.innerText = "認証"; btn.disabled = false; } } catch (e) { alert("エラーが発生しました"); btn.disabled = false; } }

async function sendToSheet() { const g = document.getElementById('genre').value; const n = document.getElementById('name').value; const d = document.getElementById('date').value; if(!g || !n || !d) return alert("すべての項目を入力してください"); const btn = document.getElementById('sendBtn'); btn.innerText = "送信中..."; btn.disabled = true; try { await fetch(GASURL, { method: 'POST', body: JSON.stringify({ genre: g, name: n, date: d }) }); alert("予約を承りました。公式LINEへ移動します。"); location.href = "https://lin.ee/K6TBvW6"; } catch (e) { alert("エラーが発生しました。直接LINEよりご連絡ください。"); location.href = "https://lin.ee/K6TBvW6"; } }
